---
- hosts: srvstack-01
  become: yes
  roles:
    - common
- hosts: srvstack-02
  become: yes
  roles:
    - common
- hosts: srvstack-03
  become: yes
  roles:
    - common
    - RedHatOfficial.rhel8_cjis
